[package]
name = "watson"
version = "0.1.0"
authors = ["Luke Tomlin <luke.tomlin@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
structopt = "0.2.18"
time = "0.1.40" # <- required for chrono duration manipulation
